version: '3.7'
services:
  pocketbase:
    image: spectado/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - 8090:80
    volumes:
      - ./pb_data:/pb_data
      - ./pb_hooks:/pb_hooks
