version: '3.7'
services:
  pocketbase:
    image: spectado/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - 8090:80
    volumes:
      - ./pocketbase/data:/pb_data
