# fly.toml app configuration file generated for rt-chat on 2023-09-25T22:11:17-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rt-chat"
primary_region = "gig"

[build.args]
  PB_VERSION="0.18.8"


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
  [http_service.concurrency]
    type = "requests"
    soft_limit = 500
    hard_limit = 550

[mounts]
  destination = "/pb/pb_data"
  source = "pb_data"
